[package]
name = "lis2dtw12-rs"
version = "0.1.0"
authors = ["Janek Graff <janek.graff@posteo.net>"]
repository = "https://github.com/JanekGraff/lis2dtw12-rs"
license = "Apache-2.0 OR MIT"
description = "no_std library for the LIS2DTW12 dual motion and temperature sensor using embedded-hal traits"
readme = "README.md"
keywords = [
    "lis2dtw12",
    "embedded-hal",
    "no_std",
    "i2c",
    "accelerometer",
    "temperature",
    "sensor",
]
categories = ["embedded", "no-std", "sensors", "hardware-support"]
edition = "2021"

exclude = [".github"]

[dependencies]
embedded-hal = { version = "1.0", optional = true }
embedded-hal-async = { version = "1.0", optional = true }
maybe-async-cfg = "0.2.1"

[dev-dependencies]
embedded-hal-mock = "0.11.1"

[features]
async = ["dep:embedded-hal-async"]
blocking = ["dep:embedded-hal"]
default = ["blocking"]

[profile.release]
lto = true
