name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RUSTFLAGS: "-Dwarnings" # Make sure CI fails on all warnings
  
jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install components
        run: rustup component add --toolchain stable rustfmt clippy

      - name: Use cache
        uses: actions/cache@v2
        
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run clippy (blocking)
        run: cargo clippy --all-targets --no-default-features --features "blocking" -- -D warnings

      - name: Run clippy (async)
        run: cargo clippy --all-targets --no-default-features --features "async" -- -D warnings
        
      - name: Run tests
        run: cargo test --all-targets --all-features